"""Initial migration.

Revision ID: d5e77344a0c4
Revises:
Create Date: 2025-03-05 00:09:10.312014

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d5e77344a0c4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_price",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # Create a trigger that fires a notify signal when a new row is inserted
    op.execute(
        """
        CREATE OR REPLACE FUNCTION notify_stock_price_insert()
        RETURNS TRIGGER AS $$
        BEGIN
            PERFORM pg_notify('stock_price_insert', row_to_json(NEW)::text);
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER stock_price_insert_trigger
        AFTER INSERT ON stock_price
        FOR EACH ROW
        EXECUTE FUNCTION notify_stock_price_insert();
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_price")
    op.execute("DROP TRIGGER IF EXISTS stock_price_insert_trigger ON stock_price;")
    op.execute("DROP FUNCTION IF EXISTS notify_stock_price_insert;")
    # ### end Alembic commands ###
